spring:
  profiles:
    active: local
    group:
      local:
        - common
      dev:
        - common
      prod:
        - common


---
spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: ${database-url}
#    username: ${db-username}
#    password: ${db-password}

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---

spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
