spring:
  profiles:
    active: local
    group:
      local:
        - common
      dev:
        - common
      prod:
        - common
      test:
        - common


---
spring:
  config:
    activate:
      on-profile: common
  datasource:
     url: ${DATABASE_URL}
     username: ${DATABASE_USERNAME}
     password: ${DATABASE_PASSWORD}
server:
  servlet:
    context-path: /api

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
